name: kh_actionnnnnn

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 저장소의 코드를 Runner에 복사
      - name: Checkout Repository
        uses: actions/checkout@v3

      #Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"

      #Build bootJar using Gradle
      - name: Build jar
        run: |
          cd app0114
          chmod +x ./gradlew
          ./gradlew clean bootJar

      # Build Docker image
      - name: Build Docker Image
        run: |
          cd app0114
          docker build -t ${{ secrets.DOCKER_HUB_ID }}/app0114:latest ./

      # Docker login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_ID }}
          password: ${{ secrets.DOCKER_HUB_PWD }}

      # Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_ID }}/app0114:latest

  Connect-to-EC2-and-Run-Container:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          key: ${{ secrets.EC2_KEY }}
          username: ubuntu
          port: 22
          script: |
            sudo docker rm -f kh_was
            sudo docker run -d --name kh_was -p 8000:8080 koreanstandardtime/app0114
